### ISSUE TITLE
add a enemy class

### ISSUE THREAD

**Issue by salehi-dev** [salehi-dev/ninja-code#1]
یک کلاس بساز که ازش بشه هر نوع دشمن یا هر نوع حیوان برای دشمن ساخته بشه

**Comment by AsefSalehi** [comment]
داده های انمی و حیوان چی باشد؟

**Comment by salehi-dev** [comment]
فعلا فقط یک کلاس بساز بعدا باز تو ایشو های بعدی از این کلاس استفاده کن
